const MATERIAS = {
  linguagens: {
    label: 'Linguagens e Códigos', icon: '✍️',
    cor: '#7F77DD', corL: '#EEEDFE', corD: '#3C3489',
    desc: 'Português, Literatura, Inglês, Artes e Educação Física',
    topicos: [
      { id:'interp', nome:'Interpretação de texto', freq:'hot', sub:'Linguagens' },
      { id:'figuras', nome:'Figuras de linguagem', freq:'hot', sub:'Linguagens' },
      { id:'modernismo', nome:'Modernismo brasileiro', freq:'hot', sub:'Literatura' },
      { id:'variacao', nome:'Variação linguística', freq:'med', sub:'Linguagens' },
      { id:'generos', nome:'Gêneros textuais', freq:'med', sub:'Linguagens' },
      { id:'romantismo', nome:'Romantismo', freq:'med', sub:'Literatura' },
      { id:'realismo', nome:'Realismo / Naturalismo', freq:'med', sub:'Literatura' },
      { id:'barroco', nome:'Barroco e Arcadismo', freq:'ok', sub:'Literatura' },
      { id:'ingles', nome:'Inglês — falso cognato', freq:'ok', sub:'Inglês' },
      { id:'semiotica', nome:'Semiótica e linguagem visual', freq:'med', sub:'Linguagens' },
      { id:'intertex', nome:'Intertextualidade', freq:'hot', sub:'Linguagens' },
      { id:'funcoes', nome:'Funções da linguagem', freq:'hot', sub:'Linguagens' },
    ],
    visao: 'Linguagens avalia como você interpreta e usa a linguagem em contextos reais — textos, imagens, músicas e até memes. São 45 questões que testam leitura crítica e domínio da norma culta.',
    historia: 'Imagine que a língua portuguesa é um rio que nasceu em Portugal, cruzou o Atlântico carregando palavras africanas e indígenas, e chegou ao Brasil transformado. Machado de Assis estava sentado na margem desse rio, pescando ironia e cinismo. Quando o Modernismo explodiu em 1922 como uma bomba na Semana de Arte Moderna, Oswald de Andrade gritou: "Tupi or not tupi, that is the question" — e a língua nunca mais foi a mesma.',
    neuro: 'Visualize o MAPA do Brasil como um texto gigante: cada estado é um parágrafo, cada cidade é uma frase. Quando você lê uma charge, você está lendo o mapa emocional do país. Sinta o cheiro de tinta de jornal velho — esse é o cheiro da Literatura Brasileira.',
    mnem: { word: 'BRRM-P', linhas: 'B — Barroco\nR — Romantismo\nR — Realismo\nM — Modernismo\nP — Pós-modernismo' },
    micro: [
      '<strong>Nível 1 — Interpretação:</strong> Toda questão tem um texto de apoio. Leia o enunciado ANTES do texto para saber o que procurar. Sublinhe palavras-chave: "autor defende", "crítica", "ironia".',
      '<strong>Nível 2 — Escolas literárias:</strong> Cada escola tem uma VIBE: Romantismo = sentimento exagerado. Realismo = crítica social fria. Modernismo = ruptura e experimentação.',
      '<strong>Nível 3 — Figuras de linguagem:</strong> Metáfora (comparação sem "como"), Metonímia (parte pelo todo), Eufemismo (suavizar), Hipérbole (exagero), Ironia (dizer o contrário).',
      '<strong>Nível 4 (avançado) — Intertextualidade:</strong> O ENEM adora textos que dialogam entre si. Perceba quando um texto cita, imita ou subverte outro. Isso é intertextualidade.',
    ],
    provas: ['Identificar o tema central e a tese do texto', 'Reconhecer figuras de linguagem em contexto', 'Relacionar características a escolas literárias', 'Interpretar linguagem não-verbal (charge, gráfico)', 'Identificar intertextualidade entre textos'],
    cranio: ['👁️ Par II (óptico): Leia com caneta colorida — sublinhe em cores diferentes por tipo de recurso', '👂 Par VIII: Leia poesias em voz alta para captar ritmo e musicalidade', '✋ Par XI: Escreva à mão os primeiros versos de cada escola literária']
  },

  humanas: {
    label: 'Ciências Humanas', icon: '🌍',
    cor: '#1D9E75', corL: '#E1F5EE', corD: '#085041',
    desc: 'História, Geografia, Filosofia e Sociologia',
    topicos: [
      { id:'rev-industrial', nome:'Revolução Industrial', freq:'hot', sub:'História' },
      { id:'2guerra', nome:'Segunda Guerra Mundial', freq:'hot', sub:'História' },
      { id:'globalizacao', nome:'Globalização', freq:'hot', sub:'Geografia' },
      { id:'ditadura', nome:'Ditadura Militar brasileira', freq:'hot', sub:'História' },
      { id:'iluminismo', nome:'Iluminismo', freq:'med', sub:'Filosofia' },
      { id:'geopolitica', nome:'Geopolítica atual', freq:'hot', sub:'Geografia' },
      { id:'urbanizacao', nome:'Urbanização', freq:'med', sub:'Geografia' },
      { id:'ambiental', nome:'Questões ambientais', freq:'hot', sub:'Geografia' },
      { id:'guerra-fria', nome:'Guerra Fria', freq:'hot', sub:'História' },
      { id:'marx-weber', nome:'Marx, Durkheim e Weber', freq:'med', sub:'Sociologia' },
      { id:'rev-francesa', nome:'Revolução Francesa', freq:'med', sub:'História' },
      { id:'colonizacao', nome:'Colonização e resistência', freq:'med', sub:'História' },
    ],
    visao: 'Ciências Humanas avalia sua capacidade de ler o mundo: entender como as sociedades se formaram no tempo e no espaço, e como as ideias filosóficas moldaram civilizações.',
    historia: 'Imagine que a história da humanidade é uma peça de teatro. O palco é a Terra. No Ato 1, os gregos acendem as luzes da razão — Sócrates pergunta "Por quê?" e é morto por isso. No Ato 3, a Revolução Industrial explode como efeito especial: fumaça, engrenagens, crianças nas fábricas. Karl Marx entra nos bastidores escrevendo um roteiro alternativo. No Ato 4, duas Guerras Mundiais destroem o palco. No Ato 5 — hoje — a globalização digitalizou o teatro: qualquer pessoa pode ser ator, diretor ou plateia ao mesmo tempo.',
    neuro: 'Sinta a fumaça negra das chaminés industriais ENTRANDO nos seus pulmões. Ouça o barulho das engrenagens. Isso é a Revolução Industrial no seu corpo. Quando estudar a Ditadura Militar, visualize uma sala silenciosa onde todos fingem não saber o que acontece no quarto ao lado — essa é a censura.',
    mnem: { word: 'CAME', linhas: 'C — Censura (AI-2)\nA — AI-5 (1968)\nM — Milagre econômico\nE — Eleição (abertura)' },
    micro: [
      '<strong>Nível 1 — Linha do tempo:</strong> Idade Antiga → Medieval → Moderna → Contemporânea. No Brasil: Colônia → Império → República → Ditadura → Redemocratização.',
      '<strong>Nível 2 — Os grandes eixos:</strong> Rev. Industrial (capitalismo), 2ª Guerra (totalitarismo), Guerra Fria (bipolaridade), Ditadura BR (autoritarismo), Globalização (mundo atual).',
      '<strong>Nível 3 — Filosofia/Sociologia:</strong> Iluminismo (Locke, Rousseau, Voltaire, Montesquieu). Sociologia clássica: Marx = classes, Durkheim = fatos sociais, Weber = ação racional.',
      '<strong>Nível 4 (avançado) — Como o ENEM pergunta:</strong> Nunca pergunta "o que foi". Pergunta "qual a relação entre X e Y?", "como isso influencia o presente?", "que princípio filosófico está presente?".',
    ],
    provas: ['Causas e consequências da Revolução Industrial', 'AI-5, censura e milagre econômico na Ditadura', 'Impactos da globalização na identidade cultural', 'Separação dos poderes (Montesquieu)', 'Diferença entre nazismo e fascismo', 'Fluxos migratórios e urbanização brasileira'],
    cranio: ['👁️ Par II: Estude mapas com cores vivas, observe charges históricas e caricaturas', '👂 Par VIII: Ouça músicas da época — MPB da Ditadura, jazz dos anos 20', '🤲 Par XI: Gesticule ao explicar rotas comerciais e movimentação de tropas']
  },

  natureza: {
    label: 'Ciências da Natureza', icon: '⚗️',
    cor: '#D85A30', corL: '#FAECE7', corD: '#712B13',
    desc: 'Química, Física e Biologia',
    topicos: [
      { id:'newton', nome:'Leis de Newton', freq:'hot', sub:'Física' },
      { id:'tabela', nome:'Tabela periódica', freq:'hot', sub:'Química' },
      { id:'dna', nome:'DNA e genética', freq:'hot', sub:'Biologia' },
      { id:'termoq', nome:'Termoquímica', freq:'med', sub:'Química' },
      { id:'eletro', nome:'Eletrostática', freq:'med', sub:'Física' },
      { id:'ecologia', nome:'Ecologia e biomas', freq:'hot', sub:'Biologia' },
      { id:'ligacoes', nome:'Ligações químicas', freq:'med', sub:'Química' },
      { id:'evolucao', nome:'Evolução das espécies', freq:'med', sub:'Biologia' },
      { id:'ondasluz', nome:'Ondas e óptica', freq:'med', sub:'Física' },
      { id:'fotossintese', nome:'Fotossíntese e respiração', freq:'hot', sub:'Biologia' },
      { id:'cinematica', nome:'Cinemática', freq:'hot', sub:'Física' },
      { id:'organica', nome:'Química orgânica', freq:'hot', sub:'Química' },
    ],
    visao: 'Ciências da Natureza une Química, Física e Biologia para explicar como o universo funciona — do átomo ao ecossistema. O ENEM foca em aplicações do cotidiano e questões ambientais.',
    historia: 'Newton estava sob uma macieira quando a maçã caiu. Mas imagine que a maçã era a dúvida de toda a humanidade: por que as coisas caem? Ele pegou aquela dúvida e transformou em 3 leis que governam tudo — do lançamento de foguetes à frenagem de um carro. Enquanto isso, Mendel na horta do mosteiro plantava ervilhas e descobria os segredos do DNA séculos antes de Watson e Crick olharem para dentro de uma célula.',
    neuro: 'SINTA a maçã batendo na sua cabeça agora. Dói? Essa dor é F = m × a. Seu crânio acelerou e sentiu a força — você viveu a 2ª Lei de Newton. Para a tabela periódica: imagine que os elementos são personagens de uma festa organizados por peso — os metais alcalinos à esquerda são os mais agitados, os gases nobres à direita ficam no canto sem se misturar com ninguém.',
    mnem: { word: 'INA', linhas: 'I — Inércia (1ª Lei de Newton)\nN — Newton F=ma (2ª Lei)\nA — Ação e Reação (3ª Lei)' },
    micro: [
      '<strong>Nível 1 — Física básica:</strong> 3 Leis de Newton, cinemática (MRU e MRUV), energia cinética e potencial. Fórmulas mais cobradas: v = d/t, F = m·a, Ec = mv²/2.',
      '<strong>Nível 2 — Química essencial:</strong> Tabela periódica (grupos e períodos), ligações (iônica, covalente, metálica), reações de combustão, pH (ácido/base).',
      '<strong>Nível 3 — Biologia central:</strong> DNA → RNA → Proteína (dogma central), mitose vs. meiose, cadeia alimentar, fotossíntese (6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂).',
      '<strong>Nível 4 (avançado):</strong> O ENEM conecta as três ciências: poluição (Química + Ecologia), vacinas (Biologia + Química), aquecimento global (Física + Química + Ecologia).',
    ],
    provas: ['Leis de Newton em situações cotidianas', 'Interpretação da tabela periódica', 'Divisão celular: mitose vs. meiose', 'Fluxo de energia nas cadeias alimentares', 'Reações de combustão e impacto ambiental', 'Genética mendeliana (dominância e recessividade)'],
    cranio: ['👁️ Par II: Desenhe diagrama de forças com vetores coloridos', '🤲 Par XI: Use as mãos para demonstrar vetores de força e aceleração', '👃 Par I: Associe cheiro de vinagre ao pH ácido, bicarbonato ao básico']
  },

  matematica: {
    label: 'Matemática', icon: '📐',
    cor: '#BA7517', corL: '#FAEEDA', corD: '#633806',
    desc: 'Álgebra, Geometria, Probabilidade e Estatística',
    topicos: [
      { id:'funcoes', nome:'Funções do 1° e 2° grau', freq:'hot', sub:'Álgebra' },
      { id:'geom-plana', nome:'Geometria plana', freq:'hot', sub:'Geometria' },
      { id:'prob', nome:'Probabilidade', freq:'hot', sub:'Estatística' },
      { id:'pa-pg', nome:'Progressões (PA e PG)', freq:'med', sub:'Álgebra' },
      { id:'trigo', nome:'Trigonometria', freq:'med', sub:'Geometria' },
      { id:'combinatoria', nome:'Análise combinatória', freq:'hot', sub:'Álgebra' },
      { id:'matrizes', nome:'Matrizes e determinantes', freq:'ok', sub:'Álgebra' },
      { id:'estatistica', nome:'Estatística descritiva', freq:'hot', sub:'Estatística' },
      { id:'geom-espacial', nome:'Geometria espacial', freq:'med', sub:'Geometria' },
      { id:'logica', nome:'Lógica e conjuntos', freq:'ok', sub:'Álgebra' },
      { id:'equacoes', nome:'Equações e inequações', freq:'hot', sub:'Álgebra' },
      { id:'financeira', nome:'Matemática financeira', freq:'hot', sub:'Álgebra' },
    ],
    visao: 'Matemática no ENEM é sempre aplicada: você resolve problemas reais de finanças, engenharia, medicina, arquitetura. Raramente é cálculo puro — o contexto é tudo.',
    historia: 'Pense na função do 2° grau como uma parábola de basquete: a bola sai da mão (vértice mínimo), sobe até o ponto máximo, e desce na cesta. O ENEM adora perguntar: "em que momento a bola atinge a altura máxima?" Toda a Bhaskara é só calcular esse ponto. Já a probabilidade é como um jogo de cartas: você nunca sabe a carta exata, mas pode calcular as chances — e isso vale da medicina à bolsa de valores.',
    neuro: 'SINTA a parábola com o seu braço: levante como um arco, aponte para baixo. Seus nervos motores gravaram a forma da função quadrática. Para probabilidade: segure um dado imaginário, sinta o peso, jogue. Quantas faces? 6. Quantas pares? 3. Metade. Simples assim.',
    mnem: { word: 'BHASKARA', linhas: 'B — Bom aluno\nH — Há que calcular\nA — Assim: x =\nS — Sinal de menos b\nK — Kopiar ±√\nA — Abrir raiz do Δ\nR — Real: Δ≥0\nA — A vezes 2 (denominador)' },
    micro: [
      '<strong>Nível 1 — Álgebra básica:</strong> Equação do 2° grau: ax² + bx + c = 0. Discriminante Δ = b² - 4ac. Se Δ > 0: duas raízes. Δ = 0: uma raiz. Δ < 0: sem raízes reais.',
      '<strong>Nível 2 — Geometria:</strong> Áreas: triângulo = base×altura/2, círculo = πr². Pitágoras: a² = b² + c². Volumes: cubo = a³, cilindro = πr²h, esfera = 4πr³/3.',
      '<strong>Nível 3 — Probabilidade e Estatística:</strong> P = casos favoráveis / total de casos. Média, mediana e moda. Gráficos: histograma, boxplot, setores.',
      '<strong>Nível 4 (avançado):</strong> Matemática financeira: juros simples (J = C·i·t) e compostos (M = C·(1+i)^t). Análise combinatória: permutação, arranjo, combinação.',
    ],
    provas: ['Bhaskara e interpretação das raízes', 'Área de figuras planas compostas', 'Probabilidade condicional', 'Gráficos estatísticos (boxplot, histograma)', 'Juros compostos em situações práticas', 'Semelhança de triângulos e razão de proporcionalidade'],
    cranio: ['🤲 Par XI: Desenhe figuras geométricas no ar com o dedo antes de calcular', '👁️ Par II: Sempre faça um esboço/diagrama antes de resolver qualquer problema', '👂 Par VIII: Verbalize os passos em voz alta — "delta igual a b ao quadrado menos..."']
  },

  redacao: {
    label: 'Redação', icon: '📝',
    cor: '#D4537E', corL: '#FBEAF0', corD: '#72243E',
    desc: 'Dissertação, Argumentação e Repertório',
    topicos: [
      { id:'estrutura', nome:'Estrutura da dissertação', freq:'hot', sub:'Redação' },
      { id:'intervencao', nome:'Proposta de intervenção', freq:'hot', sub:'Redação' },
      { id:'coesao', nome:'Coesão e coerência', freq:'hot', sub:'Redação' },
      { id:'argumentacao', nome:'Argumentação eficaz', freq:'hot', sub:'Redação' },
      { id:'competencias', nome:'5 Competências ENEM', freq:'hot', sub:'Redação' },
      { id:'repertorio', nome:'Repertório sociocultural', freq:'med', sub:'Redação' },
      { id:'conectivos', nome:'Operadores argumentativos', freq:'med', sub:'Redação' },
      { id:'introducao', nome:'Como fazer introdução', freq:'hot', sub:'Redação' },
      { id:'desenvolvimento', nome:'Parágrafos de desenvolvimento', freq:'hot', sub:'Redação' },
      { id:'temas', nome:'Temas sociais e ambientais', freq:'med', sub:'Redação' },
    ],
    visao: 'A Redação vale até 1000 pontos — pode ser seu maior diferencial. O ENEM avalia 5 competências específicas, e dominar a estrutura é o caminho mais rápido para a nota máxima.',
    historia: 'Pense na dissertação como uma casa bem construída: a Introdução é a porta de entrada com placa indicando o que tem dentro. Os parágrafos de desenvolvimento são os cômodos — cada um trata de um assunto. A Conclusão é a saída, mas você não sai de mãos vazias: deixa uma solução (proposta de intervenção) como presente para o leitor. Uma casa sem fundação (tese), sem cômodos organizados (argumentos), ou sem saída planejada (proposta) não recebe nota 1000.',
    neuro: 'Toda vez que for escrever, visualize essa CASA. Porta (introdução com tese), dois quartos (dois argumentos), saída com presente (proposta de intervenção com 5 elementos). Sinta o papel na mão, a caneta deslizando. Seu sistema motor vai associar a redação a algo concreto e físico.',
    mnem: { word: 'TADIC', linhas: 'T — Tese na introdução\nA — Argumento 1 + dado\nD — Desenvolvimento 2\nI — Intervenção (5 elementos)\nC — Conclusão retomando tese' },
    micro: [
      '<strong>Nível 1 — Estrutura básica:</strong> Introdução (2-3 linhas: contextualização + tese). Desenvolvimento 1 (argumento + dado/exemplo). Desenvolvimento 2 (argumento + dado). Conclusão (retomada + proposta).',
      '<strong>Nível 2 — As 5 Competências:</strong> C1: domínio da norma culta. C2: compreensão da proposta. C3: seleção e uso de argumentos. C4: coesão textual. C5: proposta de intervenção.',
      '<strong>Nível 3 — Proposta de intervenção perfeita:</strong> Agente (quem) + Ação (o quê) + Meio/modo (como) + Finalidade (para quê) + Efeito esperado (resultado). Todos os 5 = 200 pontos na C5.',
      '<strong>Nível 4 (avançado) — Repertório:</strong> Cite dados, leis, filósofos, fatos históricos, obras literárias. Mas sempre CONECTE ao tema. Repertório solto = desvio de tema = 0.',
    ],
    provas: ['Proposta de intervenção com os 5 elementos', 'Uso correto de conectivos (portanto, entretanto, além disso)', 'Introdução com contextualização + tese clara', 'Evitar fuga de tema e tangenciamento', 'Pontuação e concordância (C1)'],
    cranio: ['✍️ Par XII: Escreva à mão em treinos — o gesto motor fixa a estrutura', '👁️ Par II: Leia redações nota 1000 e destaque em cores cada competência', '👂 Par VIII: Leia sua redação em voz alta para ouvir erros de coesão']
  }
};
